### PR TITLE
allow optional source replica

### PR DESCRIPTION
**Pull request by minniux**
Optional set of source database replica, to be used for migration projects

### CODE REVIEW

**Review by iuriaranda — COMMENTED** [review]
hmmm isn't this what the `rds-replica` modules does already?

**Comment by minniux** [comment]
@iuriaranda  yes indeed, but this is just to use temporary for migration purpose then disable it afterwords, not to have a real read replica
I thought of using the read replica module for that, but this would mean some manual terraform state changes will be required

**Comment by iuriaranda** [comment]
🤔 hmmm I see

In any case, removing the `replicate_source_db` attribute on an existing instance will force a recreation, no?

Also, what would be the purpose of having a separate `rds-replica` module if we add this to the main module?

**Comment by minniux** [comment]
hmmm ok, make sense. I'll just close the PR and will handle the migration situation manually

**Comment by iuriaranda** [comment]
well, the answer might be to just use this module and integrate all the functionality that `rds-replica` might have into this one. But I think you'll still have some terraform state issues in your specific migration use case. So not sure it's worth it.

**Comment by iuriaranda** [comment]
@minniux what about this? Should we keep it open or can we close it?

**Pull request closed without merging**
